spring.datasource.url=${DB_DEV_URL:jdbc:postgresql://localhost:5432/reporplus2026_dev}
spring.datasource.username=${DB_DEV_USERNAME:reporplus_app}
spring.datasource.password=${DB_DEV_PASSWORD}

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.liquibase=INFO
